Reduce logging output and refactor headers
duvholt/i3-pager pull request #34
Opened 2024-05-12 21:01 UTC by Thaodan

- Refactor handling of headers, only include whats needed
- Log categorized only when logging category is enabled. #33
- Add my self to authors, correct website

2024-05-13 17:27 UTC, duvholt requested changes
Thanks for cleaning up the logging and headers handling!

Could you also add a short note in the readme on how to enable debug logging?

2024-05-13 17:27 UTC, duvholt commented on plasmoid/contents/config/main.xml
> +!-->
This somehow broke the plasmoid config. Maybe a bad xml parser?

2024-05-13 18:20 UTC, Thaodan commented on plasmoid/contents/config/main.xml
> +!-->
Could be that the `<?xml` line has to come first. Please try again.

2024-05-26 19:20 UTC, duvholt approved these changes
Thanks!

2024-05-26 19:20 UTC, merged